### ISSUE TITLE
v3.4.3-1 tracking issues

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/manta-indexer#6]
- [x] Merge relay and indexer part(Jamie, Yi).
- [x] Integration tests(Might ask Simeon and take a look at Moonbeam's tests, Jamie and Yi)
  - [x] Test all APIs indexer and relay is providing, all test cases should be written by js/ts.
  - [x] How to deploy integration tests to CI.
- [x] Benchmark result.
